
spring:
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testdb;
  h2.console.enabled: true
  jpa:
    database-platform: H2
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
  logging.level.root: trace

---
spring:
  profiles: product
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true